#!env lua

local name = "immortals"
local longname = "Immortals"
local font = "ParmaPetit-Normal.ttf"
local resolution = {1024, 768}

local libs = {
  box2d = false,
  lfs = false,
  curl = false,
  chromium = false,
}

local gl_version_expected = 1.0

local f, e = loadfile("glorp/Den")
assert(f, e)
f{name = name, longname = longname, font = font, resolution = resolution, libs = libs, gl_version_expected = gl_version_expected, targets = {...}}
